rbti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rbti_app.urls')),
]

rbti_app/urls.py
from django.urls import path
from .views import (
    BukuListView,
    BukuListViewAlt,
    BukuAvailableListView,
    MahasiswaListView,
    PeminjamanCreateView,
    PeminjamanListView,
    BukuListViewCari,
    home_page
)
app_name = "rbti_app"
urlpatterns = [
    path('', home_page, name='home'),
    path('semua-buku/', BukuListView.as_view(), name='semua-buku'),
    path('available/', BukuAvailableListView.as_view(), name='home-available'),
    path('mahasiswa/', MahasiswaListView.as_view(), name='mahasiswa'),
    path('alt/', BukuListViewAlt.as_view(), name='home-alt'),
    path('peminjaman/', PeminjamanListView.as_view(), name='peminjaman'),
    path('peminjaman/<int:id_buku>/',
         PeminjamanCreateView.as_view(), name="peminjaman"),
]

peminjaman/models.py
from django.db import models

# Create your models here.

rbti_app/models.py
from django.db import models
from django.shortcuts import reverse


class Buku(models.Model):
    id_buku = models.CharField(max_length=255, primary_key=True)
    judul = models.CharField(max_length=255)
    penulis = models.CharField(max_length=255)
    penerbit = models.CharField(max_length=255)
    tahun = models.CharField(max_length=255)

    def __str__(self):
        return self.id_buku


class Mahasiswa(models.Model):
    nim = models.BigIntegerField(primary_key=True)
    nama = models.CharField(null=False, max_length=255)
    email = models.EmailField(null=False, max_length=255, default=None)

    def __str__(self):
        return self.nama


class Peminjaman(models.Model):
    tanggal_peminjaman = models.DateField(auto_now_add=True)
    tanggal_pengembalian = models.DateField(null=True)
    nim = models.ForeignKey(Mahasiswa, on_delete=models.CASCADE)
    id_buku = models.ForeignKey(Buku, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('rbti_app:home')

# class Admin(models.Model):
#     username = models.Charfield(max_length=255, primary_key = True)
#     password = models.CharField(max_length=255)

rbti_app/forms.py
from django import forms
from django.forms.formsets import formset_factory
from django.forms import widgets

class PeminjamanForm(forms.Form):
    NIM = forms.CharField(max_length=255)
    Id_Buku = forms.CharField(max_length=255)
    Tanggal_Peminjaman = forms.DateField()

peminjaman/views.py
from django.shortcuts import render

# Create your views here.

rbti_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse
from django.contrib.postgres.search import SearchVector
from django.views.generic import ListView, CreateView
from .models import (Buku, Mahasiswa, Peminjaman)
from .forms import PeminjamanForm
from django.db import connection, DatabaseError, transaction
from django.utils import timezone
# Create your views here.


class BukuListView(ListView):
    model = Buku
    template_name = 'rbti_app/newhome.html'
    context_object_name = 'books'
    ordering = ['id_buku']


class BukuAvailableListView(ListView):
    model = Buku
    template_name = 'rbti_app/newhome.html'
    context_object_name = 'books'
    ordering = ['id_buku']

    def get_queryset(self):
        id_buku_dipinjam = get_object_or_404(
            Peminjaman, self.kwargs.get(id_buku_id='id_buku_id'))
        return Buku.objects.filter(id_buku=id_buku_dipinjam)


class BukuListViewAlt(ListView):
    model = Buku
    template_name = 'rbti_app/home.html'
    context_object_name = 'books'
    ordering = ['id_buku']


class MahasiswaListView(ListView):
    model = Mahasiswa
    template_name = 'rbti_app/mahasiswa.html'
    context_object_name = 'mahasiswa'
    ordering = 'nama'


class PeminjamanCreateView(CreateView):
    model = Peminjaman
    fields = ["nim"]

    def dispatch(self, request, *args, **kwargs):
        self.id_buku_id = get_object_or_404(Buku, pk=kwargs['id_buku'])
        print("!!!!!!!!!!!! ID BUKU ADALAH {idbuku} !!!!!!!!!!!!! ".format(
            idbuku=self.id_buku_id))
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.id_buku_id = self.id_buku_id
        form.instance.tanggal_peminjaman = timezone.now()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        data = super(PeminjamanCreateView, self).get_context_data(**kwargs)
        data['id_buku'] = Buku.objects.get(pk=self.id_buku_id)
        data['judul'] = Buku.objects.get(pk=self.id_buku_id).judul
        data['penerbit'] = Buku.objects.get(pk=self.id_buku_id).penerbit
        data['tahun'] = Buku.objects.get(pk=self.id_buku_id).tahun
        return data

        # self.id_buku_id = get_object_or_404(Buku, pk=kwargs['id_buku'])

class PeminjamanListView(ListView):
    model = Peminjaman
    template_name = 'rbti_app/peminjaman.html'
    context_object_name = 'peminjaman'

    # def get_context_data(self, **kwargs):
    #     data = super().get_context_data(**kwargs)
    #     data['buku'] = Buku.objects.get.all()

def home_page(request):
    if request.GET.get('param_cari') != '' and request.GET.get('param_cari') is not None :
        param_cari = request.GET.get('param_cari')
        context = {
            'books': Buku.objects.annotate(search=SearchVector('judul', 'penerbit', 'penulis')).filter(search=param_cari).all()
            }
        print(context)
        return render(request, 'rbti_app/newhome.html', context)
    return render(request, 'rbti_app/halaman_depan.html')

    

class BukuListViewCari(ListView):
    model = Buku
    template_name = 'rbti_app/newhome.html'
    context_object_name = 'books'
    ordering = ['id_buku']

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    

rbti_app/templates/rbti_app/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static rbti_app/css/style.css %}">
    <title>RBTI</title>
  </head>
  <body>
  <nav class="navbar navbar-light bg-light ">
  <a class="navbar-brand" href="/">RBTI</a>
</nav>
<main class="container-fluid">
  {% block content %}
  {% endblock  %}
</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

rbti_app/templates/rbti_app/halaman_depan.html
{% extends 'rbti_app/index.html' %} {% block content %}
<div class="main-page">
    <div class="main-page__title">
    <h1 style="margin-bottom: 2rem;">RBTI <br> Universitas Brawijaya</h1>
    <form action="" method="GET">
        <div class="input-group d-flex align-items-center">
            <input type="search" class="form-control" placeholder="Ketik buku, penulis atau penerbit disini" aria-label="Search"
              aria-describedby="search-addon" name="param_cari" id="param_cari"/>
            <button type="submit" class="btn btn-primary" style="width: 100px;" id="button-addon2"><i class="fas fa-search"></i></button>
          </div>
    </form>
    <p class="mt-4"><a href='/semua-buku'>Klik disini untuk melihat semua koleksi RBTI</a></p>
    </div>
</div>
{% endblock content %}

rbti_app/templates/rbti_app/home.html
{% extends 'rbti_app/base.html' %}
{% block content %}
<div class="border p-2 rounded">
<h2>Koleksi RBTI</h2>
<div class="border p-3 rounded">
<table class="table table-hover" style=margin-top:0.62rem;>
    <thead>
        <tr>
            <th>ID</th>
            <th>Judul</th>
            <th>Penulis</th>
            <th>Penerbit</th>
            <th>Tahun</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <td>{{book.id_buku}}</td>
            <td>{{book.judul}}</td>
            <td>{{book.penulis}}</td>
            <td>{{book.penerbit}}</td>
            <td>{{book.tahun}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
{% endblock  %}

rbti_app/templates/rbti_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>RBTI Universitas Brawijaya</title>
  <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'rbti_app/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <script
  src="https://kit.fontawesome.com/1e0aa6bf71.js"
  crossorigin="anonymous"
  ></script>
  <!-- Material Design Bootstrap -->
  <!-- <link rel="stylesheet" href="{% static 'rbti_app/css/mdb.min.css' %}"> -->
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'rbti_app/css/style.css' %}">
  <!-- MDBootstrap Datatables  -->
  <link href="{% static 'rbti_app/css/addons/datatables2.min.css' %}" rel="stylesheet">
</head>
<body>

  <!-- Start your project here-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">RBTI Universitas Brawijaya</a>
      <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarRightAlignExample"
      aria-controls="navbarRightAlignExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarRightAlignExample">
      <!-- Left links -->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" href="/" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/peminjaman/" aria-current="page" href="#">Peminjaman</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    </div>
  </nav>
  <main class=container>
  {% block content %}

  {% endblock  %}
  </main>
  <!-- End your project here-->

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'rbti_app/js/jquery.min.js' %} "></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'rbti_app/js/popper.min.js' %} "></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'rbti_app/js/bootstrap.min.js' %} "></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'rbti_app/js/mdb.min.js' %} "></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>
  <!-- MDBootstrap Datatables  -->
  <script type="text/javascript" src="{% static 'rbti_app/js/addons/datatables2.min.js' %}"></script>
  <script>
  $(document).ready(function () {
    $('#dtBasicExample').DataTable();
    $('.dataTables_length').addClass('bs-select');
  });
  </script>

</body>
</html>

rbti_app/templates/rbti_app/mahasiswa.html
{% extends 'rbti_app/index.html' %}
{% block content %}
<div class = "row">
<div class = "col-4">
<div class="card mt-4 main-card">
    <ul class="list-group list-group-flush">
      <a  class = "list-group-item active">List Buku</a>
    </ul>
  </div>
</div>
<div class="col-8">
<table id="dtBasicExample" class="table table-hover table-sm mt-2 main-table" cellspacing="0" width="100%">
  <thead>
        <tr>
            <th>NIM</th>
            <th>Nama</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        {% for m in mahasiswa %}
        <tr>
            <td>{{m.nim}}</td>
            <td>{{m.nama}}</td>
            <td>{{m.email}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>

<script>
$(document).ready(function () {
   $('#dtBasicExample').DataTable();
   $('.dataTables_length').addClass('bs-select');
});
</script>
{% endblock content %}

rbti_app/templates/rbti_app/newhome.html
{% extends 'rbti_app/index.html' %} {% block content %}
<div class="row">
  <div class="col-4">
    <div class="card mt-4 main-card" style="width: 80%">
      <ul class="list-group list-group-flush">
        <a class="list-group-item active">List Buku</a>
      </ul>
    </div>
  </div>
  <div class="col-8 mt-4">
  {%if books is not None%}
    <table
      id="dtBasicExample"
      class="table table-hover table-sm mt-2 main-table"
      cellspacing="0"
      width="100%"
    >
      <thead>
        <tr>
          <th>ID</th>
          <th>Judul</th>
          <th>Penulis</th>
          <th>Penerbit</th>
          <th>Tahun</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        
          {% for book in books %}
          <tr>
            <td>{{book.id_buku}}</td>
            <td>{{book.judul}}</td>
            <td>{{book.penulis}}</td>
            <td>{{book.penerbit}}</td>
            <td>{{book.tahun}}</td>
            <td>
              <a class="btn" href="{% url 'rbti_app:peminjaman' book.id_buku %}"
                >Pinjam</a
              >
            </td>
          </tr>
          {% endfor %}
    {% endif %}
      </tbody>
    </table>
  </div>
</div>

<script>
  $(document).ready(function () {
    $("#dtBasicExample").DataTable();
    $(".dataTables_length").addClass("bs-select");
  });
</script>
{% endblock content %}

rbti_app/templates/rbti_app/peminjaman.html
{% extends 'rbti_app/index.html' %} {% block content %}
<div class="row">
  <div class="col-12 mt-4">
      <h2>Peminjaman</h2>
      <hr>
    <table
      id="dtBasicExample"
      class="table table-hover table-sm mt-2 main-table"
      cellspacing="0"
      width="100%"
    >
      <thead>
        <tr>
          <th>Tanggal Peminjaman</th>
          <th>Judul</th>
          <th>Penulis</th>
          <th>Penerbit</th>
          <th>Tahun</th>
          <th>NIM Peminjam</th>
          <th>Peminjam</th>
        </tr>
      </thead>
      <tbody>
          {% for peminjam in peminjaman %}
          <tr>
            <td>{{peminjam.tanggal_peminjaman}}</td>
            <td>{{peminjam.id_buku.judul}}</td>
            <td>{{peminjam.id_buku.penulis}}</td>
            <td>{{peminjam.id_buku.penerbit}}</td>
            <td>{{peminjam.id_buku.tahun}}</td>
            <td>{{peminjam.nim.nim}}</td>
            <td>{{peminjam.nim.nama}}</td>
          </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
  $(document).ready(function () {
    $("#dtBasicExample").DataTable();
    $(".dataTables_length").addClass("bs-select");
  });
</script>
{% endblock content %}

rbti_app/templates/rbti_app/peminjaman_form.html
{% extends "rbti_app/index.html" %} {% load crispy_forms_tags %} 
{% block content %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4 mt-4">Pinjam Buku</legend>
        <p>Anda akan meminjam buku :</p>
        <table class="table">
          <tbody>
          <tr>
            <th>Judul</th>
            <td>{{judul}}</td>
          </tr>
          <tr>
            <th>Terbitan</th>
            <td>{{tahun}}</td>
          </tr>
          <tr>
            <th>Penerbit</th>
            <td>{{penerbit}}</td>
          </tr>
        </tbody>
        </table>
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Pinjam</button>
    </div>
  </form>
</div>
{% endblock content %}